import Head from 'next/head'
import NavBar from '@/components/Navbar'
import styled from 'styled-components'

const Hero = styled.div`
  width: 100vw;
  height: 300vh;
  background-color: pink;
  color: white;
  display: grid;
  place-content: center;
`

const Header = styled.header`
  .hidden-menu {
    width: 100vw;
    min-height: 100vh;
    position: fixed;
    top: 0;
    left: 0;
    background-color: lightblue;
    z-index: 998;
    display: none;

    &.open {
      display: block;
    }
  }
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <NavBar/>
        <div className='hidden-menu' onScroll={e => e.preventDefault()}></div>
        <Hero className='container'>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
        </Hero>
      </Header>
    </>
  )
}
