import Head from 'next/head'
import NavBar from '@/components/Navbar'
import styled from 'styled-components'

const Hero = styled.div`
  width: 100vw;
  height: 600vh;
  background-color: pink;
  color: white;
  display: grid;
  place-content: center;
`

const Header = styled.header`
  
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <NavBar/>
        <Hero className='container'>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat voluptatem numquam labore, repudiandae ex deleniti libero doloribus quam corrupti molestias minima iusto ipsam, necessitatibus itaque fugit ut ab alias aliquid.</p>
        </Hero>
      </Header>
    </>
  )
}
